const sessions=document.querySelector('#sessions'), status=document.querySelector('#status'), grantButton=document.querySelector('#grant'), previewButton=document.querySelector('#preview'), revokeButton=document.querySelector('#revoke');
const details=document.querySelector('#details'), projectNode=document.querySelector('#project'), sessionNode=document.querySelector('#session'), previewNode=document.querySelector('#previewDetails'), tabPreview=document.querySelector('#tabPreview'), originsNode=document.querySelector('#origins');
const connectionNode=document.querySelector('#connection');
const uploadSection=document.querySelector('#uploadSection'),uploadDetails=document.querySelector('#uploadDetails'),approveUpload=document.querySelector('#approveUpload');let uploadChoice=null;
const visualSection=document.querySelector('#visualSection'),visualStatus=document.querySelector('#visualStatus'),visualRequest=document.querySelector('#visualRequest'),grantVisualButton=document.querySelector('#grantVisual'),revokeVisualButton=document.querySelector('#revokeVisual');
const clickSection=document.querySelector('#clickSection'), clickStatus=document.querySelector('#clickStatus'), clickRequestNotice=document.querySelector('#clickRequestNotice'), previewClickButton=document.querySelector('#previewClick');
const clickPreviewNode=document.querySelector('#clickPreview'), clickPreviewScope=document.querySelector('#clickPreviewScope'), clickPreviewOrigins=document.querySelector('#clickPreviewOrigins'), grantClickButton=document.querySelector('#grantClick'), revokeClickButton=document.querySelector('#revokeClick');
let state={pending:[],grants:[]}, preview=null, clickPreview=null;
const choiceKey='opencode-bridge-session-choice';
function selected(){const key=sessions.value;return state.pending.find(p=>p.key===key)||state.grants.find(g=>g.key===key);}
function clearPreview(){preview=null;previewNode.hidden=true;grantButton.disabled=true;}
function clearClickPreview(){clickPreview=null;clickPreviewNode.hidden=true;grantClickButton.disabled=true;}
function formatExpiry(expiry){if(expiry==null)return '';const date=new Date(expiry);return Number.isNaN(date.getTime())?'':date.toLocaleString();}
function updateClickUI(){const item=selected();const isGrant=!!item&&state.grants.some(g=>g.key===item.key);if(!isGrant){clickSection.hidden=true;clearClickPreview();return;}clickSection.hidden=false;const click=item.click;if(click&&click.enabled){const expiry=formatExpiry(click.expiresAt);clickStatus.textContent=`Interaction access: enabled${expiry?` (expires ${expiry})`:''}.`;revokeClickButton.hidden=false;}else{clickStatus.textContent='Interaction access: not granted. The agent can read pages in this session but cannot click or type into them.';revokeClickButton.hidden=true;}const req=item.clickRequest;clickRequestNotice.hidden=!(req&&Array.isArray(req.origins)&&req.origins.length);clearClickPreview();}
function updateChoice(){const item=selected();if(!item){details.hidden=true;previewButton.disabled=true;clearPreview();updateClickUI();visualSection.hidden=true;return;}details.hidden=false;projectNode.textContent=`Project: ${item.project}`;sessionNode.textContent=`Session: ${item.session}`;previewButton.disabled=false;chrome.storage.local.set({[choiceKey]:item.key});clearPreview();updateClickUI();const g=state.grants.find(x=>x.key===item.key);visualSection.hidden=!g;visualStatus.textContent=g?.visual?.enabled?`Screenshots allowed for ${g.visual.origin} until ${formatExpiry(g.visual.expiresAt)}.`:'Screenshots require separate permission for one tab and origin.';const r=g?.visualRequest;visualRequest.hidden=!r;visualRequest.textContent=r?`Request: ${r.origin} (tab ${r.handle}).`:'';grantVisualButton.hidden=!r;revokeVisualButton.hidden=!g?.visual?.enabled;}
async function refresh(){state=await chrome.runtime.sendMessage({type:'get-state'})||{pending:[],grants:[],uploadPending:[]};connectionNode.textContent=state.nativeError?`Native host error: ${state.nativeError}`:(state.nativeConnected?'Native host: connected':'Native host: connecting');sessions.replaceChildren();for(const p of state.pending){const o=document.createElement('option');o.value=p.key;o.textContent=`Pending · ${p.label}`;sessions.append(o);}for(const g of state.grants){const o=document.createElement('option');o.value=g.key;o.textContent=`Approved · ${g.label}`;sessions.append(o);}const saved=await chrome.storage.local.get(choiceKey);if(saved[choiceKey]&&[...sessions.options].some(o=>o.value===saved[choiceKey]))sessions.value=saved[choiceKey];else sessions.selectedIndex=-1;revokeButton.disabled=!state.grants.length;updateChoice();const p=(state.uploadPending||[]).find(x=>x.key===sessions.value);uploadChoice=p||null;uploadSection.hidden=!p;if(p){uploadDetails.textContent=`${p.project} · ${p.session} · ${p.origin}\nTab: ${p.target?.title||'(untitled)'} · input ${p.target?.ref||'?'} · accept ${p.target?.accept||'(any)'} · form action origin ${p.target?.formActionOrigin||'(none)'}\n${p.displayPath}\n${p.name} · ${p.size} bytes · SHA-256 ${p.sha256}`;approveUpload.disabled=false;}if(!state.pending.length&&!state.grants.length)status.textContent='No pending or approved sessions. Send a bridge request first.';}
previewButton.addEventListener('click',async()=>{status.textContent='';const item=selected();if(!item){status.textContent='Select a session explicitly.';return;}const origins=item.requestedOrigins||(item.nonce?item.origins:[])||[];if(!origins.length){status.textContent='No origins proposed. Retry the bridge request with requested origins.';return;}preview={key:item.key,origins:origins.slice(),nonce:item.nonce};tabPreview.replaceChildren();for(const origin of origins){const li=document.createElement('li');li.textContent=origin;tabPreview.append(li);}originsNode.textContent=`Origins: ${origins.join(', ')}. The bridge can open and read pages at these origins using your signed-in browser session.`;previewNode.hidden=false;grantButton.disabled=false;});
grantButton.addEventListener('click',async()=>{status.textContent='';const item=selected();if(!item||!preview||preview.key!==item.key){status.textContent='Preview the selected session and origins first.';return;}grantButton.disabled=true;try{if(!await chrome.permissions.request({origins:preview.origins.map(o=>o+'/*')}))throw Error('Host permission denied.');const result=await chrome.runtime.sendMessage({type:'grant',key:item.key,origins:preview.origins,nonce:preview.nonce});if(result?.error)throw Error(result.error);status.textContent=`Approved ${result.origins.join(', ')} for ${item.project} / ${item.session}.`;clearPreview();}catch(e){status.textContent=e.message||'Approval failed.';grantButton.disabled=false;}await refresh();});
revokeButton.addEventListener('click',async()=>{const g=state.grants.find(x=>x.key===sessions.value);if(!g){status.textContent='Select an approved session.';return;}const r=await chrome.runtime.sendMessage({type:'revoke',key:g.key});status.textContent=r?.error||`Revoked ${g.label}.`;await refresh();});
 previewClickButton.addEventListener('click',()=>{status.textContent='';const item=selected();const req=item&&item.clickRequest;if(!item||!req||!Array.isArray(req.origins)||!req.origins.length){status.textContent='No interaction access requested for this session.';return;}clickPreview={key:item.key,nonce:req.nonce,origins:req.origins.slice()};clickPreviewScope.textContent=`Project: ${item.project} · Session: ${item.session}`;clickPreviewOrigins.replaceChildren();for(const origin of req.origins){const li=document.createElement('li');li.textContent=origin;clickPreviewOrigins.append(li);}clickPreviewNode.hidden=false;grantClickButton.disabled=false;});
grantClickButton.addEventListener('click',async()=>{status.textContent='';const item=selected();if(!item||!clickPreview||clickPreview.key!==item.key){status.textContent='Preview click access for the selected session first.';return;}grantClickButton.disabled=true;try{const result=await chrome.runtime.sendMessage({type:'grant-click',key:item.key,nonce:clickPreview.nonce});if(result?.error)throw Error(result.error);status.textContent=`Click access enabled for ${item.project} / ${item.session}.`;clearClickPreview();}catch(e){status.textContent=e.message||'Enabling click access failed.';grantClickButton.disabled=false;}await refresh();});
revokeClickButton.addEventListener('click',async()=>{status.textContent='';const item=selected();if(!item){status.textContent='Select a session first.';return;}const result=await chrome.runtime.sendMessage({type:'revoke-click',key:item.key});status.textContent=result?.error||`Click access revoked for ${item.project} / ${item.session}.`;await refresh();});
sessions.addEventListener('change',updateChoice);refresh();
grantVisualButton.addEventListener('click',async()=>{const g=state.grants.find(x=>x.key===sessions.value),r=g?.visualRequest;if(!r)return;grantVisualButton.disabled=true;try{if(!await chrome.permissions.request({permissions:['debugger']}))throw Error('Debugger permission denied.');const result=await chrome.runtime.sendMessage({type:'grant-visual',key:g.key,nonce:r.nonce});if(result?.error)throw Error(result.error);status.textContent='Screenshot access granted for 30 minutes.';}catch(e){status.textContent=e.message||'Screenshot approval failed.';grantVisualButton.disabled=false;}await refresh();});
revokeVisualButton.addEventListener('click',async()=>{await chrome.runtime.sendMessage({type:'revoke-visual',key:sessions.value});await refresh();});
approveUpload.addEventListener('click',async()=>{const p=uploadChoice;if(!p)return;approveUpload.disabled=true;try{if(!await chrome.permissions.request({permissions:['debugger']}))throw Error('Debugger permission denied.');const r=await chrome.runtime.sendMessage({type:'grant-upload',key:p.key,stageId:p.stageId,nonce:p.nonce});if(r?.error)throw Error(r.error);status.textContent='File approved for this upload request only.';}catch(e){status.textContent=e.message||'File approval failed.';approveUpload.disabled=false;}await refresh();});
let checks=0;
const diagnostic=setInterval(async()=>{
  if(++checks>8){clearInterval(diagnostic);return;}
  try {const result=await chrome.runtime.sendMessage({type:'get-state'});connectionNode.textContent=result.nativeError?`Native host error: ${result.nativeError}`:(result.nativeConnected?'Native host: connected':'Native host: connecting');}
  catch(error){connectionNode.textContent=`Native host error: ${error.message}`;}
},1000);
