const sessions=document.querySelector('#sessions'), status=document.querySelector('#status'), grantButton=document.querySelector('#grant'), previewButton=document.querySelector('#preview'), revokeButton=document.querySelector('#revoke');
const details=document.querySelector('#details'), projectNode=document.querySelector('#project'), sessionNode=document.querySelector('#session'), previewNode=document.querySelector('#previewDetails'), tabPreview=document.querySelector('#tabPreview'), originsNode=document.querySelector('#origins');
const connectionNode=document.querySelector('#connection');
let state={pending:[],grants:[]}, preview=null;
const choiceKey='opencode-bridge-session-choice';
function selected(){const key=sessions.value;return state.pending.find(p=>p.key===key)||state.grants.find(g=>g.key===key);}
function clearPreview(){preview=null;previewNode.hidden=true;grantButton.disabled=true;}
function updateChoice(){const item=selected();if(!item){details.hidden=true;previewButton.disabled=true;clearPreview();return;}details.hidden=false;projectNode.textContent=`Project: ${item.project}`;sessionNode.textContent=`Session: ${item.session}`;previewButton.disabled=false;chrome.storage.local.set({[choiceKey]:item.key});clearPreview();}
async function refresh(){state=await chrome.runtime.sendMessage({type:'get-state'})||{pending:[],grants:[]};connectionNode.textContent=state.nativeError?`Native host error: ${state.nativeError}`:(state.nativeConnected?'Native host: connected':'Native host: connecting');sessions.replaceChildren();for(const p of state.pending){const o=document.createElement('option');o.value=p.key;o.textContent=`Pending · ${p.label}`;sessions.append(o);}for(const g of state.grants){const o=document.createElement('option');o.value=g.key;o.textContent=`Approved · ${g.label}`;sessions.append(o);}const saved=await chrome.storage.local.get(choiceKey);if(saved[choiceKey]&&[...sessions.options].some(o=>o.value===saved[choiceKey]))sessions.value=saved[choiceKey];else sessions.selectedIndex=-1;revokeButton.disabled=!state.grants.length;updateChoice();if(!state.pending.length&&!state.grants.length)status.textContent='No pending or approved sessions. Send a bridge request first.';}
previewButton.addEventListener('click',async()=>{status.textContent='';const item=selected();if(!item){status.textContent='Select a session explicitly.';return;}const origins=item.requestedOrigins||(item.nonce?item.origins:[])||[];if(!origins.length){status.textContent='No origins proposed. Retry the bridge request with requested origins.';return;}preview={key:item.key,origins:origins.slice(),nonce:item.nonce};tabPreview.replaceChildren();for(const origin of origins){const li=document.createElement('li');li.textContent=origin;tabPreview.append(li);}originsNode.textContent=`Origins: ${origins.join(', ')}. The bridge can open and read pages at these origins using your signed-in browser session.`;previewNode.hidden=false;grantButton.disabled=false;});
grantButton.addEventListener('click',async()=>{status.textContent='';const item=selected();if(!item||!preview||preview.key!==item.key){status.textContent='Preview the selected session and origins first.';return;}grantButton.disabled=true;try{if(!await chrome.permissions.request({origins:preview.origins.map(o=>o+'/*')}))throw Error('Host permission denied.');const result=await chrome.runtime.sendMessage({type:'grant',key:item.key,origins:preview.origins,nonce:preview.nonce});if(result?.error)throw Error(result.error);status.textContent=`Approved ${result.origins.join(', ')} for ${item.project} / ${item.session}.`;clearPreview();}catch(e){status.textContent=e.message||'Approval failed.';grantButton.disabled=false;}await refresh();});
revokeButton.addEventListener('click',async()=>{const g=state.grants.find(x=>x.key===sessions.value);if(!g){status.textContent='Select an approved session.';return;}const r=await chrome.runtime.sendMessage({type:'revoke',key:g.key});status.textContent=r?.error||`Revoked ${g.label}.`;await refresh();});
sessions.addEventListener('change',updateChoice);refresh();
let checks=0;
const diagnostic=setInterval(async()=>{
  if(++checks>8){clearInterval(diagnostic);return;}
  try {const result=await chrome.runtime.sendMessage({type:'get-state'});connectionNode.textContent=result.nativeError?`Native host error: ${result.nativeError}`:(result.nativeConnected?'Native host: connected':'Native host: connecting');}
  catch(error){connectionNode.textContent=`Native host error: ${error.message}`;}
},1000);
