const sessions=document.querySelector('#sessions'), status=document.querySelector('#status'), grantButton=document.querySelector('#grant'), previewButton=document.querySelector('#preview'), revokeButton=document.querySelector('#revoke');
const details=document.querySelector('#details'), projectNode=document.querySelector('#project'), sessionNode=document.querySelector('#session'), previewNode=document.querySelector('#previewDetails'), tabPreview=document.querySelector('#tabPreview'), originsNode=document.querySelector('#origins');
let state={pending:[],grants:[]}, preview=null;
const choiceKey='opencode-bridge-session-choice';
function selected(){const key=sessions.value;return state.pending.find(p=>p.key===key)||state.grants.find(g=>g.key===key);}
function clearPreview(){preview=null;previewNode.hidden=true;grantButton.disabled=true;}
function updateChoice(){const item=selected();if(!item){details.hidden=true;previewButton.disabled=true;clearPreview();return;}details.hidden=false;projectNode.textContent=`Project: ${item.project}`;sessionNode.textContent=`Session: ${item.session}`;previewButton.disabled=false;chrome.storage.local.set({[choiceKey]:item.key});clearPreview();}
async function refresh(){state=await chrome.runtime.sendMessage({type:'get-state'})||{pending:[],grants:[]};sessions.replaceChildren();for(const p of state.pending){const o=document.createElement('option');o.value=p.key;o.textContent=`Pending · ${p.label}`;sessions.append(o);}for(const g of state.grants){const o=document.createElement('option');o.value=g.key;o.textContent=`Approved · ${g.label}`;sessions.append(o);}const saved=await chrome.storage.local.get(choiceKey);if(saved[choiceKey]&&[...sessions.options].some(o=>o.value===saved[choiceKey]))sessions.value=saved[choiceKey];else sessions.selectedIndex=-1;revokeButton.disabled=!state.grants.length;updateChoice();if(!state.pending.length&&!state.grants.length)status.textContent='No pending or approved sessions. Send a bridge request first.';}
async function readSelection(){const tabs=await chrome.tabs.query({highlighted:true,currentWindow:true});if(!tabs.length||tabs.some(t=>!Number.isInteger(t.id)))throw Error('Highlight one or more tabs in this window.');const origins=[...new Set(tabs.map(t=>{try{const u=new URL(t.url);if(u.protocol==='https:'||(u.protocol==='http:'&&u.hostname==='127.0.0.1'))return u.origin;}catch{}throw Error('Only HTTPS and http://127.0.0.1 tabs can be approved.');}))];return{tabs:tabs.map(t=>({id:t.id,title:t.title||'',url:t.url})),origins};}
previewButton.addEventListener('click',async()=>{status.textContent='';const item=selected();if(!item){status.textContent='Select a session explicitly.';return;}try{const selection=await readSelection();preview={key:item.key,...selection};tabPreview.replaceChildren();for(const t of selection.tabs){const li=document.createElement('li');li.textContent=`${t.title} — ${t.url}`;tabPreview.append(li);}originsNode.textContent=`Origins: ${selection.origins.join(', ')}`;previewNode.hidden=false;grantButton.disabled=false;}catch(e){clearPreview();status.textContent=e.message||'Preview failed.';}});
grantButton.addEventListener('click',async()=>{status.textContent='';const item=selected();if(!item||!preview||preview.key!==item.key){status.textContent='Preview the selected session and tabs first.';return;}try{const latest=await readSelection();if(JSON.stringify(latest.tabs.map(t=>t.id))!==JSON.stringify(preview.tabs.map(t=>t.id))||JSON.stringify(latest.origins.slice().sort())!==JSON.stringify(preview.origins.slice().sort())){clearPreview();status.textContent='Highlighted tabs changed. Review a new preview.';return;}const missing=[];for(const origin of preview.origins)if(!await chrome.permissions.contains({origins:[origin+'/*']}))missing.push(origin+'/*');if(missing.length&&!await chrome.permissions.request({origins:missing}))throw Error('Host permission denied.');const result=await chrome.runtime.sendMessage({type:'grant',key:item.key,tabIds:preview.tabs.map(t=>t.id),origins:preview.origins});if(result?.error)throw Error(result.error);status.textContent=`Approved ${result.origins.join(', ')} for ${item.label}.`;clearPreview();}catch(e){status.textContent=e.message||'Approval failed.';}await refresh();});
revokeButton.addEventListener('click',async()=>{const g=state.grants.find(x=>x.key===sessions.value);if(!g){status.textContent='Select an approved session.';return;}const r=await chrome.runtime.sendMessage({type:'revoke',key:g.key});status.textContent=r?.error||`Revoked ${g.label}.`;await refresh();});
sessions.addEventListener('change',updateChoice);refresh();
